### PR TITLE
:sparkles: Add image preview project in readme. Close #9

### LINKED ISSUE #9: Readme, preview project
It would be nice to have a preview of the project in the readme, if that makes sense to you, you can assign me that tweak. Thanks.

### PR DESCRIPTION
**Pull request by BrunoLagoa**

### CODE REVIEW

**Review by Malte2036 — CHANGES_REQUESTED** [review]
Can you also embed a picture from feed? Only the login page is not enough. 
Maybe the feed page on the tablet and the login page on the monitor.

**Comment by BrunoLagoa** [comment]
> 

I can't log in with google, the screen is going blank... there's a way to take the print and attach it to the project, so we can modify it.

**Comment by Malte2036** [comment]
image

**Comment by BrunoLagoa** [comment]
Cool, I'll update the pr, thanks

**Comment by BrunoLagoa** [comment]
@Malte2036  hi, image updated. 😎

**Comment by BrunoLagoa** [comment]
@Malte2036 Hello, If possible, would you like to add the tags to this pr, hacktoberfest, hacktoberfest-accepted. to participate in the event.

**Comment by BrunoLagoa** [comment]
If possible, would you like to add the tags to this pr, hacktoberfest, hacktoberfest-accepted. to participate in the event.

**Pull request merged**
